name: 'Deploy Simple To Heroku'
description: 'This is a very simple GitHub action that allows you to deploy to Heroku'
branding:
  icon: 'upload-cloud'
  color: 'orange'
inputs:
  heroku_api_key:
    description: 'This will be used for authentication. You can find it in your heroku homepage account settings'
    required: true
  heroku_email:
    description: 'Email that you use with heroku'
    required: true
  heroku_app_name:
    description: 'The appname to use for deploying/updating'
    required: true
outputs:
  status:
    description: 'The success/failure of the action of pushing changes to the remote heroku repository'
runs:
  using: 'node16'
  main: 'dist/index.js'
